#include<iostream>
using namespace std;
main()
{
 int one;
cout<<" Number 1 :";
cin>>one;
int two;
cout<<" Number 2 :";
cin>>two;
int three;
cout<<" Number 3 :";
cin>>three;
int four;
cout<<" Number 4 :";
cin>>four;
int five;
cout<<" Number 5 :";
cin>>five;
int six;
cout<<" Number 6 :";
cin>>six;
int seven;
cout<<" Number 7 :";
cin>>seven;
int eight;
cout<<" Number 8 :";
cin>>eight;
int nine;
cout<<" Number 9 :";
cin>>nine;
int ten;
cout<<" Number 10 :";
cin>>ten;
int eleven;
cout<<" Number 11 :";
cin>>eleven;
int twelve;
cout<<" Number 12 :";
cin>>twelve;
int thirteen;
cout<<" Number 13 :";
cin>>thirteen;
int fourteen;
cout<<" Number 14 :";
cin>>fourteen;
int fifteen;
cout<<" Number 15 :";
cin>>fifteen;
int addfirstfive;
addfirstfive = one + two + three + four + five ;
int multiplysecfive;
multiplysecfive = six * seven * eight * nine * ten ;
int minuslastfive;
minuslastfive = eleven - twelve - thirteen - fourteen - fifteen ;
int addtheaddedandmultiplied;
 addtheaddedandmultiplied = addfirstfive + multiplysecfive ;
int subtractfinal;
subtractfinal = addtheaddedandmultiplied - minuslastfive;
cout<<" The ultimate result is :"<<subtractfinal;
}